# Generated by Django 4.2.4 on 2023-08-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scategory",
                        to="home.categorymodel",
                    ),
                ),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="RealEstateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("price", models.IntegerField()),
                ("meterage", models.IntegerField()),
                ("address", models.TextField()),
                ("bathroom_and_toilet", models.IntegerField(blank=True)),
                ("bedroom", models.IntegerField(blank=True)),
                ("detail", models.TextField()),
                ("descriptions", models.TextField()),
                ("main_image", models.ImageField(upload_to="real_estates/%Y/%m/%d/")),
                ("image1", models.ImageField(upload_to="real_estates/%Y/%m/%d/")),
                ("image2", models.ImageField(upload_to="real_estates/%Y/%m/%d/")),
                ("image3", models.ImageField(upload_to="real_estates/%Y/%m/%d/")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("available", models.BooleanField(default=True)),
                (
                    "type_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realestate",
                        to="home.categorymodel",
                    ),
                ),
            ],
            options={"ordering": ("type_category",),},
        ),
        migrations.DeleteModel(name="About",),
    ]
