# Generated by Django 4.2.4 on 2023-08-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_categorymodel_realestatemodel_delete_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scategory",
                to="home.categorymodel",
            ),
        ),
    ]
