# Generated by Django 4.2.4 on 2023-08-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_categorymodel_sub_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="categorymodel", name="sub_category",),
        migrations.AddField(
            model_name="categorymodel",
            name="transaction",
            field=models.CharField(
                choices=[("فروش", "فروش"), ("اجاره", "اجاره")],
                default="فروش",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="realestatemodel",
            name="year_of_construction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
