# Generated by Django 4.2.4 on 2023-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_categorymodel_sub_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="propertytype",
            field=models.CharField(
                choices=[
                    ("مسکونی", "مسکونی"),
                    ("ویلایی", "ویلایی"),
                    ("آپارتمان", "آپارتمان"),
                    ("خانه های تک خانوار", "خانه های تک خانوار"),
                    ("دفاتر", "دفاتر"),
                    ("زمین", "زمین"),
                    ("زمین کشاورزی", "زمین کشاورزی"),
                    ("باغ", "باغ"),
                ],
                default="مسکونی",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="name",
            field=models.CharField(default="none", max_length=200, unique=True),
        ),
    ]
