# Generated by Django 4.2.4 on 2023-08-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_categorymodel_propertytype_alter_categorymodel_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel", options={"ordering": ("propertytype",)},
        ),
        migrations.AddField(
            model_name="realestatemodel",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="realestatemodel",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
