# Generated by Django 4.2.4 on 2023-08-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_categorymodel_options_realestatemodel_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="categorymodel", name="name",),
    ]
